theme: jekyll-theme-minimal
title: Fugu Games
url: http://technicat.com/
description: various old mini games made in Unity
show_downloads: true
logo: /images/icons/cat/catglasses.svg
privacy: These games don't collect data outside of the Unity game engine

