theme: jekyll-theme-minimal
title: Fugu Games
url: http://technicat.com/
description: various old mini games made in Unity
show_downloads: true
logo: /images/icons/cat/catglasses.svg
appstore: https://apps.apple.com/us/developer/technicat-llc/id295241742
privacy: These games don't collect data outside of the Unity game engine

